name    'cnacorrea-puppet'
version '0.1.0'
author 'cnacorrea'
license 'Apache License, Version 2.0'
summary 'This is a small beginning for a Puppet management module.'
description 'This is a small beginning for a Puppet management module.'
project_page 'https://github.com/cnacorrea/cnacorrea-puppet'

dependency 'puppetlabs/inifile', '>= 1.0.3'
dependency 'puppetlabs/apache', '>= 1.0.1'
dependency 'puppetlabs/puppetdb', '>= 3.0.1'